import os
root = '/mlainas/yewon/bp-benchmark/code/train/real_model'
join = os.path.join
model_fold = {"bcg": {0: {0: join(root, 'bcg-resnet1d-fold0-original-seed0.ckpt'),
                      1: join(root, 'bcg-resnet1d-fold1-original-seed0.ckpt'),
                      2: join(root, 'bcg-resnet1d-fold2-original-seed0.ckpt'),
                      3: join(root, 'bcg-resnet1d-fold3-original-seed0.ckpt'),
                      4: join(root, 'bcg-resnet1d-fold4-original-seed0.ckpt')},
                      1: {0: join(root, 'bcg-resnet1d-fold0-original-seed1.ckpt'),
                      1: join(root, 'bcg-resnet1d-fold1-original-seed1.ckpt'),
                      2: join(root, 'bcg-resnet1d-fold2-original-seed1.ckpt'),
                      3: join(root, 'bcg-resnet1d-fold3-original-seed1.ckpt'),
                      4: join(root, 'bcg-resnet1d-fold4-original-seed1.ckpt')},
                      2: {0: join(root, 'bcg-resnet1d-fold0-original-seed2.ckpt'),
                      1: join(root, 'bcg-resnet1d-fold1-original-seed2.ckpt'),
                      2: join(root, 'bcg-resnet1d-fold2-original-seed2.ckpt'),
                      3: join(root, 'bcg-resnet1d-fold3-original-seed2.ckpt'),
                      4: join(root, 'bcg-resnet1d-fold4-original-seed2.ckpt')}},
              "ppgbp":{0: {0: join(root, 'ppgbp-resnet1d-fold0-original-seed0.ckpt'),
                      1: join(root, 'ppgbp-resnet1d-fold1-original-seed0.ckpt'),
                      2: join(root, 'ppgbp-resnet1d-fold2-original-seed0.ckpt'),
                      3: join(root, 'ppgbp-resnet1d-fold3-original-seed0.ckpt'),
                      4: join(root, 'ppgbp-resnet1d-fold4-original-seed0.ckpt')},
                      1: {0: join(root, 'ppgbp-resnet1d-fold0-original-seed1.ckpt'),
                      1: join(root, 'ppgbp-resnet1d-fold1-original-seed1.ckpt'),
                      2: join(root, 'ppgbp-resnet1d-fold2-original-seed1.ckpt'),
                      3: join(root, 'ppgbp-resnet1d-fold3-original-seed1.ckpt'),
                      4: join(root, 'ppgbp-resnet1d-fold4-original-seed1.ckpt')},
                      2: {0: join(root, 'ppgbp-resnet1d-fold0-original-seed2.ckpt'),
                      1: join(root, 'ppgbp-resnet1d-fold1-original-seed2.ckpt'),
                      2: join(root, 'ppgbp-resnet1d-fold2-original-seed2.ckpt'),
                      3: join(root, 'ppgbp-resnet1d-fold3-original-seed2.ckpt'),
                      4: join(root, 'ppgbp-resnet1d-fold4-original-seed2.ckpt')}},
              "sensors": {0: {0: join(root, 'sensors-resnet1d-fold0-original-seed0.ckpt'),
                      1: join(root, 'sensors-resnet1d-fold1-original-seed0.ckpt'),
                      2: join(root, 'sensors-resnet1d-fold2-original-seed0.ckpt'),
                      3: join(root, 'sensors-resnet1d-fold3-original-seed0.ckpt'),
                      4: join(root, 'sensors-resnet1d-fold4-original-seed0.ckpt')},
                      1: {0: join(root, 'sensors-resnet1d-fold0-original-seed1.ckpt'),
                      1: join(root, 'sensors-resnet1d-fold1-original-seed1.ckpt'),
                      2: join(root, 'sensors-resnet1d-fold2-original-seed1.ckpt'),
                      3: join(root, 'sensors-resnet1d-fold3-original-seed1.ckpt'),
                      4: join(root, 'sensors-resnet1d-fold4-original-seed1.ckpt')},
                      2: {0: join(root, 'sensors-resnet1d-fold0-original-seed2.ckpt'),
                      1: join(root, 'sensors-resnet1d-fold1-original-seed2.ckpt'),
                      2: join(root, 'sensors-resnet1d-fold2-original-seed2.ckpt'),
                      3: join(root, 'sensors-resnet1d-fold3-original-seed2.ckpt'),
                      4: join(root, 'sensors-resnet1d-fold4-original-seed2.ckpt')}},
              "uci2": {0:"/data2/taero/bp-benchmark/code/train/model_original/uci2-resnet1d-fold0-test_sp=16.588-test_dp=8.298.ckpt",}
              }
